spyder-ide/qtpy

- AUTHORS.md
- setup.py
I think this is the work of the whole team. Several people have contributed to the Spyder shim to improve things and fix bugs through the years, besides Pierre and me. So they should be acknowledged here too :-)
This is an example I'm following from the Jupyter team. In all their packages the listed author is the whole team, not someone in particular.
> Cite the whole Spyder Development Team as author (besides Colin)

- qtpy/QtGui.py
- qtpy/QtWidgets.py
Instead of importing all of `{PyQt4, Pyside}.QtGui` in those modules, now we import exactly what's needed to maintain compatibility with PyQt5.
> Use the right PyQt4/PySide QtGui classes in QtWidgets and QtGui

- qtpy/QtWidgets.py
This is an error I discovered while testing another app that's using qtpy.
> QtWidgets: Remove objects that belong to QtCore

- qtpy/__init__.py
- tests/tests.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:spyder-ide:qtpy?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:spyder-ide:qtpy?groups=code_patterns/%3A4ACGxFj1)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Prefer `format()` over string interpolation operator" issue

- qtpy/QtWebEngineWidgets.py
There is functionality that only belongs to one or the other of these Qt web backends. So we need a constant to determine when we're using each one :-)
> Add constant to QtWebEngineWidgets to see if we are using WebEngine or WebKit

- .travis.yml
- appveyor.yml
- tests/test_main.py
Over at the Astropy project, we've developed [ci-helpers](https://github.com/astropy/ci-helpers), which is a set of well tested scripts to help with setting up conda environments for continuous integration. This is not at all astronomy specific and we are interested in getting other projects to adopt it too. This PR shows how you can use it in the Travis configuration, and also adds a configuration file for AppVeyor, in case you would like to turn that on. I've also enabled OSX testing on Travis.
[to see the benefits of using ci-helpers, note that this PR only adds a net 6 lines but that includes adding the appveyor configuration]
If you are interested in going ahead with this, try turning on AppVeyor and I'll force push to this branch again to trigger a build.
Note that …
> Use ci-helpers (from Astropy) for CI and enable AppVeyor

- qtpy/QtWidgets.py
- It belongs to QtCore in PyQt5.
- This finishes PR #31.
----
@astrofrog, sorry I missed this one in my review. We follow the philosophy of removing objects belonging to two modules to avoid confusions among our users.
This also makes people to really use the Qt5 layout.
> Remove QItemSelectionModel from QtWidgets for PyQt4 and PySide

- qtpy/QtCore.py
- qtpy/QtDesigner.py
- qtpy/QtGui.py
- qtpy/QtNetwork.py
- qtpy/QtPrintSupport.py
- qtpy/QtSvg.py
- qtpy/QtTest.py
- qtpy/QtWebEngineWidgets.py
- qtpy/QtWidgets.py
- qtpy/__init__.py
- qtpy/compat.py
- tests/test_main.py
This is easier on the users, and the tests are currently failing because of this problem.
I got rid of the `os.environ[QT_API]` lookups, because it makes qtpy rely too much on an external global state, while the environent is already pared in `__init__.py`. This makes the import thread safe, for example.
With this I think that https://github.com/spyder-ide/spyder/pull/3210 won't fail anymore.
> Ignore case for QT_API env variable in qtpy submodules

- qtpy/QtTest.py
In QtTest.py, it says:
```python
"""
Provides QtTest and functions
.. warning:: PySide is not supported here, that's why there is not unit tests
running with PySide.
"""
```
However, if I replace the exception that is currently raised for PySide with:
```python
from PySide.QtTest import QTest
```
it works fine. Is there any reason not to do this?
> QtTest for PySide

- qtpy/uic.py
- tests/test_uic.py
This is a follow-up to https://github.com/spyder-ide/qtpy/pull/27 (and will be rebased once that is merged) which includes auto-loading of custom widget classes by parsing the ui files. This then makes the behavior of loadUi consistent with that in PyQt4/5.
This is still a work in progress - I need to test this extensively with glue to make sure that it always works. I'm also not entirely happy with the sys.path hack, and want to try and find a better solution. As such, this is not ready for a proper review, but any preliminary feedback/suggestions would be useful (will be easier to see the changes here once #27 is merged)
> Automatically load custom widget classes when using PySide

- qtpy/_patch/qcombobox.py
- tests/test_patch_qcombobox.py
For now, I'm adding a regression test to make sure it fails on Travis/AppVeyor. This includes #37 and should be rebased once #37 is merged.
> Fix remaining segmentation fault that occurs with the patched QComboBox in PySide

- qtpy/__init__.py
I think that ``__version__`` should be set to the actual QtPy version, otherwise packages won't be able to easily check for example that QtPy is recent enough to include certain patches. I think we could then make the Qt and other versions available via e.g.
```
qtpy.QT_VERSION
qtpy.PYSIDE_VERSION
qtpy.PYQT4_VERSION
qtpy.PYQT5_VERSION
```
I'd be happy to include a quick PR to include in QtPy 1.1 if others agree?
Of course, we could have ``qtpy.QTPY_VERSION`` be the QtPy version, but I think it would be counter-intuitive for ``__version__`` to not be that.
> qtpy.__version__ should be QtPy version, not Qt version

- qtpy/__init__.py
Fixes #42. This change follows #41.
> Don't check PyQt version with qtpy's version for old PyQt versions

- qtpy/__init__.py
- Since qtpy is just a wrapper, there's no other way to tell external processes started by a PyQt/PySide application the Qt toolkit its parent is running on.
- Because of this, not setting QT_API was breaking Spyder's IPython kernels and Python consoles.
> Make qtpy to set the QT_API environment variable

- qtpy/QtCore.py
Fixes #36.
Fixes #35.
I still think that the duplicate imports are very weird and not needed, But it doesn't hurt too much to leave them.
> Remove PyQt variant symbols from QtCore

- README.md
you've got an amazing project name here and it's self-explanatory, don't explain the joke
http://tvtropes.org/pmwiki/pmwiki.php/Main/DontExplainTheJoke
> Remove reference to how qtpy is pronounced in README

- circle.yml
It really makes no sense, given that we are testing qtpy itself.
> Don't install qtpy as a conda package in CircleCI

- qtpy/QtMultimedia.py
- qtpy/tests/test_qtmultimedia.py
Add a wrapper around QtMultimedia to provide access to QAudio, QSound
and friends.
Closes #49
Signed-off-by: David Aguilar <davvid@gmail.com>
> Add support for QtMultimedia

- qtpy/QtSvg.py
@ccordoba12, @Nodd should we delete `PYQT4, PYQT5, PYSIDE, PythonQtError` from the module at the end?
`del PYQT4, PYQT5, PYSIDE, PythonQtError` ?
> PR: Add explicit imports to QtSvg module

- qtpy/QtCore.py
- qtpy/QtDesigner.py
- qtpy/QtGui.py
- qtpy/QtMultimedia.py
- qtpy/QtNetwork.py
- qtpy/QtPrintSupport.py
- qtpy/QtSvg.py
- qtpy/QtTest.py
- qtpy/QtWebEngineWidgets.py
- qtpy/QtWidgets.py
- qtpy/__init__.py
- qtpy/_patch/qcombobox.py
- qtpy/compat.py
- qtpy/uic.py
I only need QtCore, QtGui, QtWidgets, so it would be nice if I can vendor-in part of the qtpy project. Having relative imports makes this much easier.
> PR: Use relative imports so its vendored more easily

- qtpy/QtCore.py
- qtpy/QtWidgets.py
> Move QStringListModel to QtCore

- MANIFEST.in
Debian, and other Linux distributions, recommends to source upstream Python code from PyPI. However, current releases of `QtPy` are missing the test suite. The latter is desirable for both the package build and CI process in Debian.
This PR includes the test suite to the output of `sdist`. Following the merge of this PR, please consider submitting a new `1.2.0.1` or `1.2.1` release with the included test suite.
Cheers,
Ghis
> PR: Include test suite in sdist

- qtpy/QtGui.py
- qtpy/QtWidgets.py
PyQt4 4.6 on Centos 6.8 reports itself as:
PyQt4.x86_64 4.6.2-9.el6 @base
PyQt4-devel.x86_64 4.6.2-9.el6 @base
This version is missing symbols from QtGui that causes qtpy to
fail.  Allow `import qtpy` to work in this environment.
Signed-off-by: David Aguilar <davvid@gmail.com>
> PR: Add support for PyQt 4.6

- .coveragerc
- .coveralls.yml
This skips the `tests` directory and other files we don't plan/need to test.
> PR: Add a coveragerc file

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/tests/test_qdesktopservice_split.py
Fixes #89
The QDesktopServices from Qt4 has been split into two namespaces,
QDesktopServices and QStandardPaths, this allows a pyqt5 import of
QStandardPaths to work with pyqt4.
`from qtpy.QtCore import QStandardPaths`
I'm not sure if this is the best way to do it
> PR: Honor QStandardPaths location in Qt5

- README.md
> PR: Update Readme to mention that we now support PySide2.

- qtpy/tests/test_qtdesigner.py
- qtpy/tests/test_qtnetwork.py
- qtpy/tests/test_qtprintsupport.py
- qtpy/tests/test_qtsvg.py
- qtpy/tests/test_qttest.py
Fixes #110
I didn't add tests for QtOpenGL, because the usage of this module is discouraged http://doc.qt.io/qt-5/qtopengl-index.html
> PR: Add tests for Qtdesigner, QtNetwork, QtPrintSupport, QtSvg and QtTest.

- README.md
https://github.com/spyder-ide/qtpy/pull/114#discussion_r115598912
> PR: Update Readme to reflect that we actually use the PySide2 layout

- MANIFEST.in
> PR: No cache files included in the release tarball

- qtpy/_patch/qheaderview.py
- qtpy/tests/test_patch_qheaderview.py
This is a second attempt at fixing #119 according to the request from @ccordoba12 in https://github.com/spyder-ide/qtpy/pull/120#issuecomment-318371899 :
Warn instead of raising an exception if QHeaderView deprecated methods
are used. Also adapt unit tests accordingly.
Fixes #119
Closes #120
> PR: Warn if QHeaderView deprecated methods are used

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/tests/test_qdesktopservice_split.py
Fixes: #131
I added the missing `QtCore.QStandardPaths.writableLocation()` and allow the import of `QDesktopServices` methods in PYQT4
> PR: Changes to QDesktop split 

- qtpy/__init__.py
Fixes #138.
See #138 for rationale.
> PR: If a Qt binding is already imported, then use it.

- qtpy/QtHelp.py
- qtpy/QtMultimedia.py
- qtpy/__init__.py
- qtpy/tests/test_qthelp.py
- qtpy/tests/test_qtmultimedia.py
> PR: Add QtHelp Wrapper

- circle.yml
- qtpy/__init__.py
> PR: Avoid using PyQt5.Qt, which imports unneeded stuff and forces discrete GPU on OSX

- qtpy/QtCore.py
tested for `PySide2-5.11.0a1-5.11.0-cp36-cp36m-win_amd64.whl` and pyzo master.
It's sufficient to make pyzo works, so we are in the good direction..
It's not sufficient for Spyder to work, though.
> PR: Add better compatibility with PySide2

- appveyor.yml
- ci/test-pyqt4.sh
- ci/test-pyside.sh
- ci/test-pyside2.sh
- circle.yml
- qtpy/QtHelp.py
- qtpy/QtMultimedia.py
- qtpy/tests/test_qdesktopservice_split.py
- qtpy/tests/test_qthelp.py
- qtpy/tests/test_qtmultimedia.py
- qtpy/tests/test_qtnetwork.py
- qtpy/tests/test_qtsvg.py
This also removes some limitations for PySide2 due to our use of old wheels.
> PR: Use Qt official wheels to run tests for PySide2

- qtpy/QtQuickWidgets.py
- qtpy/tests/test_qtquickwidgets.py
This PR adds support for QtQuickWidgets.
> PR: Add QtQuickWidgets

- qtpy/QtCharts.py
- qtpy/tests/test_qtcharts.py
atm i didnt add a check whether the QtChart module for PyQt5 is installed (needs to be installed separately for PyQ5, in PySide2 it is included by default). How do you want me to do it? Simple Try-catch? Or not needed?
> PR: Add QtCharts module support

- qtpy/__init__.py
Situation: user has already imported PyQt4 and QT_API is set to pyqt.
qtpy will issue a spurious warning complaining that initial_api pyqt is different from selected one pyqt4, even if they are the same.
This code will make sure that in case of pre-loaded QT modules, the API is reset to the same initial_api if compatible, otherwise to the default.
> PR: Prevent warnings for equivalent APIs

- .circleci/install.sh
- .circleci/test-pyqt4.sh
- .circleci/test-pyqt5.sh
- .circleci/test-pyside.sh
- .circleci/test-pyside2.sh
Conda-forge doesn't provide updated packages to keep testing this.
> PR: Skip testing PyQt4 and PySide in Python 3.5

- qtpy/py3compat.py
Silence deprecation warnings seen on Python3.7:
qtpy/py3compat.py:76:
DeprecationWarning: Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import MutableMapping
> PR: Avoid deprecated "from collections import MutableMapping"

- .circleci/test-pyside2.sh
- qtpy/Qt3DAnimation.py
- qtpy/Qt3DCore.py
- qtpy/Qt3DExtras.py
- qtpy/Qt3DInput.py
- qtpy/Qt3DLogic.py
- qtpy/Qt3DRender.py
This is failing due to a bug in Shiboken.
Fixes #195.
> PR: Don't load Qt3D modules for buggy versions of PySide2

- qtpy/__init__.py
In response to this thread:
https://github.com/spyder-ide/qtpy/issues/192
-J
----
Fixes #192.
> PR: Add FORCE_QT_API environment variable

- qtpy/compat.py
- qtpy/py3compat.py
- qtpy/uic.py
* Importing ABC from collections module will raise `ImportError` in Python 3.9 and raises `DeprecationWarning` from 3.4 . Hence use `collections.abc` and also preserve compatibility with Python 2. Ref : https://github.com/python/cpython/pull/10596
* ~Use `list` instead of deprecated getchildren in Python 3. #206 #238~
> PR: Add Python 3.9 compatibility for `collections.abc` module

- qtpy/__init__.py
As mentioned in #222 i stumbled across this.
before:
after (expected behaviour):
It seems obvious to me and i spare further explination.
> PR: Fix imported modules logic if 'FORCE_QT_API' is empty

- qtpy/QtWidgets.py
In other words:
- From PyQt5 : `from PyQt5.QtWidgets import QStyleOptionFrame`
- From PyQt4: `from PyQt4.QtWidgets import QStyleOptionFrameV3`
- From QtPy: `from qtpy.QtWidgets import QStyleOptionFrame`
> PR: Add support for QStyleOptionFrameV3 from PyQt4

- qtpy/QtSerialPort.py
- qtpy/tests/test_qtserialport.py
This adds support for QtSerialPort add-on. Unfortunately for now it is only available in PyQt5, not even in PySide2.
> PR: Add support for QtSerialPort add-on

- qtpy/tests/test_uic.py
- qtpy/uic.py
The purpose of this PR is to provide and API function (`loadUiType`) that is available in PyQt4/PyQt5 but not in PySide/PySide2.
Accordingly to what has been done for `loadUi` the new function is implemented in the `qtpy/uic.py` module and it is used only if a native implementation is not provided by the selected Qt bindings.
The `loadUiType` function load a Qt Designer .ui file and return the generated form class and the Qt base class, which is useful for customizing (e.g. adding methods) classes generated by the Qt designer.
Basic unit tests are provided as well.
> PR: Add loadUiType implementation for PySide2

- qtpy/tests/test_uic.py
Otherwise we get:
```
from qtpy import uic
/usr/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py:142: in _import
return original_import(name, *args, **kwargs)
qtpy/uic.py:88: in <module>
from pyside2uic import compileUi
/usr/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py:142: in _import
return original_import(name, *args, **kwargs)
E   ModuleNotFoundError: No module named 'pyside2uic'
```
This module is not guaranteed to be present since it was removed in newer versions of pyside2(-tools)
See also: https://github.com/spyder-ide/qtpy/pull/202
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>
> qtpy/tests/test_uic.py: skip if pyside2uic not installed

- qtpy/uic.py
> PR: Wrap `pysideuic` and `pyside2uic` imports since they could be unavailable

- .github/workflows/ci.yml
- .github/workflows/test.sh
Coveralls is now showing 0 coverage after PR #262 . This PR will fix it, as well as implement some other low-hanging fruit fixes and improvements on top of that.
As it turns out, it was indeed due to the test working dir not matching the one coveralls was running in, due to the hacky workaround to fix the issues from QtPy having a non-`src` dir layout.
Not only does this fix the issue with coveralls, but it also makes the paths much cleaner, reports coverage from all jobs and with descriptive job names, and combines coverage across all bindings (since naturally a lot of code is specific to one binding), along with fixing/cleaning up a few other things. This makes our total coverage much higher and more representative, bringing it from 25% to 75%, a 3x improvement, as well as makes the …
> PR: Fix and improve Coveralls reporting

- qtpy/QtCharts.py
- qtpy/QtCore.py
- qtpy/__init__.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtdesigner.py
- qtpy/tests/test_qtsvg.py
- qtpy/tests/test_uic.py
- qtpy/uic.py
Fixes a number of minor problems in the codebase, including:
> PR: Prevent future deprecations messages and decrease general technical debt + code style issues

- qtpy/__init__.py
#225 somehow reverted the fix for the broken `FORCE_QT_API` that was fixed in #230.  presumably a merge fail... not sure if there are others
on current master (this pretty much destroys environments with multiple Qt backends)
```py
In [1]: import PySide6
In [2]: from qtpy import QtCore
In [3]: QtCore.QTimer
Out[3]: PyQt6.QtCore.QTimer
```
> PR: Fix regression in FORCE_QT_API behavior from merging PySide6 support

- qtpy/__init__.py
As discussed in [#85 (comment)](https://github.com/spyder-ide/qtpy/issues/85#issuecomment-963393873), especially if we're going to keep around old non-constant top-level variables that were only used internally (`is_old_pyqt` and `is_pyqt46`), we may as well keep the `PYQT4` and `PYSIDE` module-level constants around (always `False` now) for backward compatibility, and easier cross-compat between QtPy versions.
> PR: Add back legacy PYQT4 and PYSIDE package-level constants for compat

- CONTRIBUTING.md
Adds a Contributing Guide based on the one for `spyder-docs-sphinx-theme`, which you both previously reviewed and provided a number of helpful suggestions and improvements on (all of which are, of course, incorporated here), and also mirroring where applicable the versions in the website, docs, theme and other repos.
In addition to find-replacing the QtPy project and repo names and eliminating content that isn't relevant, a number of other sections tailored to the specifics of QtPy were added, including:
* A detailed `Running the Tests` section (per #66 )
* A description of installing and selecting Python Qt binding(s) to test against
* An outline of the main branches, and which to use (``master``, aside from critical/security fixes or when otherwise directed)
* More appropriate branch …
> PR: Add Contributing Guide based on other Spyder projects

- qtpy/__init__.py
- qtpy/_version.py
> PR: Catch `PythonQtError` when trying to do alias for `QtDataVisualization` and dev version correction

- .github/workflows/ci.yml
- qtpy/__init__.py
We will now warn developers (via a `DeprecationWarning`, so they have to be running Python with `-X dev`, `-W default` or `-W error`, or import QtPy in their `__main__` script) when they are using long-deprecated, soon to be removed Qt4 based APIs (PySide and PyQt4), either via their explictly set preference, via import, or via a default fallback if installed, all of which will be unsupported come QtPy 2.0.
Resolves #261
> PR: Add a warning for developers still running legacy Qt4-based APIs

- qtpy/py3compat.py
The PY2 code path was not importing Callable, which breaks the
compat module when it tries to import Callable from py3compat.
Signed-off-by: David Aguilar <davvid@gmail.com>
> PR: Import Callable and MutableMapping in py3compat for Python 2 compat

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/QtWidgets.py
- qtpy/compat.py
- qtpy/enums_compat.py
- qtpy/sip.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtwidgets.py
> PR: Unscoped enums access for PyQt6 and other missing PyQt6 compatibility changes

- .github/workflows/ci.yml
- .github/workflows/test.sh
- RELEASE.md
- pyproject.toml
- qtpy/__init__.py
- qtpy/_version.py
- setup.cfg
- setup.py
Currently, the package is using the deprecated legacy builder and calling setup.py directly, which is causing warnings and will eventually go away completely. This migrates it to the (more) modern PEP 517 setuptools builder and setup.cfg, with a setup setup.py for backward compatibility. This also makes one change to how the version is handled to avoid having to import the package or execute any dynamic code to get the version statically, which shouldn't affect anything else as `_version` is marked as internal use only (with leading `_`). I've compared the wheels and sdists and, aside from the minor updates to the metadata made in a separate commit, they are byte for byte identical.
Resolve #270
> PR: Upgrade packaging to avoid legacy/deprecated behavior and follow PEP 517

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/QtPrintSupport.py
- qtpy/QtSql.py
- qtpy/QtWidgets.py
This PR fixes #286.
All `exec_`s of PySide6 are simply mapped (assigned) to `exec`s to avoid the following DeprecationWarning of PySide6.
```
DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead.
sys.exit(app.exec_())
```
I think if there is no problem if `exec_` is overwritten, this PR can be merged.
If a way to access the original `exec_` is required, QtPy may provides the option for controlling the overwrite or the special attribute for accessing original `exec_`.
> PR: Map exec_ to their non-deprecated alternatives

- qtpy/QtTextToSpeech.py
- qtpy/tests/test_qttexttospeech.py
I made this PR to support #232.
Note that QtTextToSpeech is available in Qt5 only and has not been supported in Qt6 yet.
https://www.qt.io/product/qt6/qt-5-15-vs-6-2-feature-comparison
> Qt Speech
> Due to its limited adoption in Qt 5, we are still studying whether to port this add-on module to Qt 6. Please let us know whether and how you are using this module. Existing projects can pull the relevant code from the 5.15 branch into their project.
And, PyQt5 >= 5.15.1 or PySide2 (>= first 5.11.0) supports QtTextToSpeech.
The copyright and license part in QtTextToSpeech.py is copy of QtXml.py.
> PR: Add QtTextToSpeech Module

- qtpy/__init__.py
As discussed in #284 , adds a `DeprecationWarning` on QtPy 1.x for Qt5/PyQt5 versions below 5.9 and PySide2 versions below 5.12.
@dalthviz the merge to 1.x will be rather non-trivial (replacing distutils with packaging, changing the warning type, fixing merge conflicts, and possibly a tweak to the message to include users as well, etc) so I'm happy to take care of that too, if you'd like.
Closes #284
> PR: Add warning for deprecated/EoL Qt5 & PyQt5/PySide2 versions to fix #284

- qtpy/QtTest.py
- qtpy/tests/test_qttest.py
I made this PR to fix #197.
I use promote_enums  in QtTest.
In Current QtPy, promote_enums is used in QtCore/QtGui/QtWidgets only, but is there any reason?
> PR: Import all classes in QtTest module.

- .github/workflows/ci.yml
- .github/workflows/test.sh
- qtpy/__init__.py
Followup to merging PR #289 to `master` following a very weird and unexpected check failure on Win 10 + PyQt 5.9 + conda + Python 3.6; see [CI logs](https://github.com/spyder-ide/qtpy/pull/292#issue-793185869).
Seems like there's some weird behavior on this very specific CI run, where the tests pass, but when we run the command to save the path for the test coverage, which imports QtPy a _second_ time in a new instance of the same interpreter, `QT_VERSION` is not defined, which must mean that all the `if` blocks either didn't trigger or had an `ImportError` and QtPy fell back to using PyQt5. I could understand if PyQt 5.9 didn't define those top-level constants (since the source repo is not public, I tried to check beforehand but couldn't), but the fact that it worked without error the …
> PR: Define Qt/binding versions at top level, fix warnings if versions not found, and fix test dir on CIs

- RELEASE.md
Update `RELEASE.md` following current branch structure (`master` and `1.x`) and add some missing info
> PR: Update RELEASE.md for 1.x version

- qtpy/__init__.py
Per the discussion in #233 , adds a minimum version check for Qt6 and each binding to ensure they are at least version 6.2.0 or higher, since we don't officially support anything under that. Also, refactors the constants a bit accordingly.
Closes #233 (again)
> PR: Add minimum version check for Qt6 >=6.2.0

- .github/workflows/ci.yml
- .github/workflows/test.sh
- qtpy/tests/test_uic.py
- setup.cfg
Adds Python 3.10 to the CIs, and official support to the packaging metadata, and takes care of a few related warnings.
Also, simplifies the CI config a bit, unskips the Linux PySide6 Py3.6 wheels since they are now available (the macOS ones now are too, but they are failing on the latest macOS), and skips PySide2 for now on Python 3.10, since it doesn't (yet) support it.
Fixes #269
> PR: Add support for Python 3.10 on CIs and packaging

- qtpy/QtCore.py
(found while trying to patch Pyzo for PyQt6-6.2.2)
> make QLibraryInfo.location works

- README.md
> PR: Update README.md adding a line for QtPy usefulness when migrating between Qt bindings/versions

- qtpy/QtWidgets.py
For some reason they moved it to QtGui.
FWIW, I'm doing some CI builds for Pyzo, and the one for Linux/py39/PyQt6 broke on this. After the proposed change, it worked. Also see https://stackoverflow.com/questions/66872811/is-the-icon-functionality-of-qfilesystemmodel-broken-in-pyqt6-on-windows?noredirect=1&lq=1
> PR: Fix QFileSystemModel for PyQt6

- .github/workflows/ci.yml
ref: https://github.com/spyder-ide/qtpy/pull/308#issuecomment-1000834513
> PR: Set CI job's timeout to 10 min to force a stalled test to terminate

- .github/workflows/ci.yml
- .github/workflows/test.sh
- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
- setup.cfg
Fixes #311 
Edit: Also fixes an issue with PyQt6 and sip to use `mightBeRichText`:
> PR: Add missing `QtGui` utility function to `QtCore.Qt` for PySide bindings

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
Fixes #306 
Note: Needs a rebase after #313 is merged
> PR: Add mapping for missing enum values aliases on `QtCore.Qt`

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/QtPrintSupport.py
- qtpy/QtSql.py
- qtpy/QtWidgets.py
I'm sorry, #305 is caused by my PR: #287.
I'm trying to fix and add tests. 
(I sent a pull request to see if tests using QApplication would work with CI.)
NOTE: This PR can be closed without merging when more appropriate fixes and tests are provided.
Fixes #305
> PR: Fix mappings of instance method and slot alias (PyQt6 and PySide6)

- qtpy/QtCharts.py
- qtpy/__init__.py
- qtpy/tests/test_qtcharts.py
Fixes #304
Note: Needs a rebase after #313 is merged
> PR: Add `QtCharts` alias for backward compatibility with 1.x

- qtpy/QtCore.py
- qtpy/enums_compat.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtwidgets.py
A number of enum values in QT can be accessed through aliases. For example, QSlider.TicksPosition has both TicksAbove  and TicksLeft and TicksLeft is an alias of TicksAbove.
Currently, enums are only iterated which yield their variants but miss the existence of aliases. This patch explicitly iterate over the enum members to catch all aliases. Tests are included, both for TicksLeft which is a documented alias (https://doc.qt.io/qt-6/qslider.html#TickPosition-enum) and SC_SliderGroove which happens to have the same value as SC_ScrollBarAddLine and hence appears as an alias.
> PR: Promote enum aliases

- .github/workflows/test.sh
- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/tests/conftest.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtmultimediawidgets.py
- qtpy/tests/test_qtprintsupport.py
- qtpy/tests/test_qtsql.py
- qtpy/tests/test_qtwidgets.py
- qtpy/tests/test_qtwinextras.py
- qtpy/tests/test_uic.py
- qtpy/tests/utils.py
- setup.cfg
> PR: Add missing tests for aliased methods

- .github/workflows/ci.yml
- .github/workflows/test.sh
- MANIFEST.in
- setup.cfg
Presently, Pytest's ``--importmode=importlib`` causes our test suite to fail at collection due to a regression introduced in Pytest 7.0.0, pytest-dev/pytest#9645 . This was fixed in pytest-dev/pytest#9681 , but hasn't yet made it into a Pytest release. Therefore, we work around it for now by disabling ``--importmode=importlib``.
Fixes #324
> PR: Restrict broken Pytest versions to those not affected by the Pytest 7.0.0 import-mode=importlib behavior regression

- qtpy/uic.py
Monkey patch UIParser.readResources to make it works with Python 3.9. Without this patch, we get this error:
> Traceback (most recent call last):
File "simple.py", line 12, in <module>
MainWindowUI, MainWindowBase = uic.loadUiType(UI_FILE)
File "\Miniconda3\envs\pysideads\lib\site-packages\qtpy\uic.py", line 271, in loadUiType
compileUi(fd, code_stream, indent=0, from_imports=from_imports)
File "\Miniconda3\envs\pysideads\lib\site-packages\pyside2uic\__init__.py", line 144, in compileUi
winfo = ui_comp.compileUi(uifile, pyfile, from_imports)
File "\Miniconda3\envs\pysideads\lib\site-packages\pyside2uic\Compiler\compiler.py", line 91, in compileUi
w = self.parse(input_stream)
File "\Miniconda3\envs\pysideads\lib\site-packages\pyside2uic\uiparser.py", line 882, in parse
actor(elem)
File …
> PR: Monkey patch UIParser for Python 3.9 compatibility

- qtpy/compat.py
`QFileDialog.Options` does not exist on Qt6.
Tested with PyQt5 5.15.2 and PyQt6 6.2.3
> PR: Use QFileDialog.Option to be compatiable with Qt6

- qtpy/QtOpenGL.py
- qtpy/tests/test_qtopengl.py
`QOpenGLTimeMonitor` and `QOpenGLTimerQuery` do not exist on some architectures such as armhf; the PyQt5 and PySide2 code has a check for whether these should be included in the package. Since they are imported unconditionally, importing `qtpy.QtOpenGL` fails on those architectures.  This patch imports those two classes within a try/except block to allow for this to gracefully fail, and comments out the corresponding assertions in the test suite.
> PR: Skip import of QOpenGLTime* on architectures where not available

- .github/workflows/ci.yml
- .github/workflows/test.sh
- qtpy/tests/test_uic.py
> PR: Fix uic skipped tests and PyQt 6.3.0 segfaulting tests

- qtpy/QtGui.py
- qtpy/tests/test_qtgui.py
See commit message/comment in code for details.
> PR: Add workaround for `mode` argument in QTextCursor.movePosition (Pyside2)

- qtpy/__init__.py
- qtpy/tests/conftest.py
- qtpy/tests/test_main.py
I'm not 100% sure what the intention of modifying `os.environ` at all is, but assuming it's meant to set it so that e.g. new processes that spawn make use of the same framework, then there's a bug in the current implementation in `master`:
```
>>> import os
>>> import PyQt6
>>> 'QT_API' in os.environ
False
>>> import qtpy
>>> qtpy.API  # good
'pyqt6'
>>> 'QT_API' in os.environ  # okay...
True
>>> os.environ['QT_API']  # bad
'pyqt5'
```
This bug was found precisely because a pattern like this: have no QT_API set, import PyQt6, then import qtpy, then spawn a new process (using joblib), have it fail because in that process `import qtpy` fails because PyQt5 isn't installed, but `os.environ['QT_API'] == 'pyqt5'`.
This PR thus avoids changing `os.environ` at all until a suitable API has been …
> PR: Fix bug with environ handling

- README.md
- qtpy/__init__.py
- qtpy/tests/conftest.py
- qtpy/tests/test_cli.py
- qtpy/tests/test_main.py
> PR: Change bindings `try order` to be `PyQt5, PySide2, PyQt6, PySide6`

- qtpy/QtGui.py
- qtpy/tests/test_qtgui.py
> PR: Add workaround for `mode` argument in QTextCursor.movePosition (PySide6)

- README.md
Per discussion in #352 , this adds a note to the readme about usage with Pyright under the Type Checker Integration section. Thanks, @adam-grant-hendry!
Resolves #352
> PR: Add note to readme about use with Pyright

- qtpy/compat.py
- qtpy/tests/test_compat.py
Fixes #302 
This just adds a wrapper around the sip.isdeleted and shiboken.isValid functions
> PR: Add wrapper around sip/shiboken isdeleted/isvalid (compat.py)

- qtpy/QtCore.py
small fix that allows IDEs to find QtCore.Qt in PyQt6
> PR: Fix PyQt6 typing import for Qt

- README.md
> PR: Add initial `Methods, helpers and QtPy namespace specifics` section to the README

- .github/workflows/ci.yml
Seems like the env for Windows with Python 3.7 and PyQt 5.9 on the CI is not working
> CI: Ensure conda-forge channel usage when testing with conda

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
This adds toPython() compat functions to QDate and QTime for symmetry.
> PR: toPython helpers for QDate and QTime

- README.md
I just noticed that there are small typos in variable names in Readme.
> PR: Fix typo in Qt flags in Readme

- qtpy/QtGui.py
- qtpy/QtWidgets.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtwidgets.py
> PR: Aliased `QUndoCommand`, provided `QLineEdit.getTextMargins()` and `QFontMetricsF.width()`

- qtpy/__init__.py
> PR: Add missing `self` for `QtBindingsNotFoundError` definition

- qtpy/QtCore.py
I think this isn't needed, at least ``Qt.MouseButton.MiddleButton`` seems to exist with PySide6 6.2, 6.3, and 6.4. In 6.4 re-assigning this leads to an actual error.
Fixes https://github.com/spyder-ide/qtpy/issues/373
> Don't re-assign Qt.MouseButton.MiddleButton on PySide6

- .github/workflows/ci.yml
- .github/workflows/test.sh
- qtpy/QtCore.py
- qtpy/tests/test_qtdesigner.py
- qtpy/tests/test_qtsensors.py
- qtpy/tests/test_qtserialport.py
- qtpy/tests/test_qtsvg.py
- seems QLibraryInfo.location crashes with conda on the CI job (ok locally), so skip that one
- qtdesigner is not available yet on conda, so can be other modules, we allow that to avoid some tests to fail if the package is not installed
> CI: Try PySide6 on conda

- .github/workflows/ci.yml
- qtpy/tests/test_qt3danimation.py
- qtpy/tests/test_qtmultimediawidgets.py
- qtpy/tests/test_qtpositioning.py
- qtpy/tests/test_qtqml.py
- qtpy/tests/test_qtquick.py
- qtpy/tests/test_qtquickwidgets.py
- qtpy/tests/test_qtwebchannel.py
- qtpy/tests/test_qtwebsockets.py
the disabled classes QCameraViewfinder, QSGAbstractRenderer& QSGEngine are qt5-only
> PR: Enable more qt6 tests

- .codespellrc
- .github/workflows/ci.yml
- .github/workflows/test.sh
- .pre-commit-config.yaml
I will push to and test this incrementally, starting with setting one job to 6.4 for bindings and Qt, and see how things go. If we need to fix a lot of failures (which I might need your help on @dalthviz ), we can merge this once that's done and then add the optional deps in a separate PR, since that can be significantly more complex.
Fixes #375 
Part of #345
> PR: Expand the CI test matrix with Qt/bindings 6.4 and fix tests with PyQt 5.9

- qtpy/QtPdf.py
- qtpy/QtPdfWidgets.py
- qtpy/tests/test_qtpdf.py
- qtpy/tests/test_qtpdfwidgets.py
> PR: Add QtPdf

- qtpy/__init__.py
As described in #390 , this fixes the `raise QtBindingsNotFoundError` in `__init__,py` to correctly use `raise ... from None`, to ensure it behaves appropriately and has a clear, understandable and non-confusing message.
Here's how the error output looked previously:
```python
>>> import qtpy.QtCore
Traceback (most recent call last):
File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\qtpy\qtpy\__init__.py", line 252, in <module>
from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\qtpy\qtpy\__init__.py", line 259, in <module> …
```
> PR: Use raise from None when raising QtBindingsNotFoundError in __init__

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
> PR: Fix `LibraryLocation` -> `LibraryPath` renaming due to deprecation with Qt6

- .github/workflows/ci.yml
- .github/workflows/test.sh
- pyproject.toml
- setup.cfg
As discussed in #386 , adds official support for Python 3.11 (following a similar template to #296 which added 3.10 support) in the Trove tags and CI tests, making the necessary binding and Qt version adjustments as required for the 3.11 jobs, including a somewhat non-ideal but necessary workaround for [a conda package solver incompatibility](https://github.com/spyder-ide/qtpy/pull/392#issuecomment-1356123618) on Py311 + pyqt 5.15 + qt 5.15.
Along the way, I've refactored the CI config to centralize the binding and Qt API version selection all in one place in the matrix config, to greatly reduce duplication of version constants and the scattering of the logic multiple places in the declarative config and the dynamic execution script. In concert with that, I've been able to:
* Ensure that …
> PR: Add Python 3.11 to CIs/tags & overhaul CI config

- qtpy/__init__.py
Currently, as noted in issue #395 , a generic `RuntimeWarning` is emitted when falling back to a non-selected binding, instead of QtPy's own `PythonQtWarning` subclass. Furthermore, the text could perhaps be clarified a bit. I also noticed a few other issues when making this changed, which I fixed.
Therefore, this PR:
* Emits a `PythonQtWarning` instead of a generic `RuntimeWarning` when falling back to an unselected binding, consistent with the other warnings and errors that use QtPy-specific subclasses
* Has `PythonQtWarning` inherit from `RuntimeWarning` instead of a generic `Warning` , to be consistent with all the other errors and warnings and with what `RuntimeWarning` is meant for, and ensure the previous replacement is fully backwards compatible
* Tweaks the message text of the …
> PR: Make warning usage consistant and refine messages

- .github/workflows/ci.yml
As discussed on #400 and a followup to PR #392, unskip PySide2 on Python 3.11, because it works just fine now (at least after #397).
> PR: Unskip PySide2 5.15 on Python 3.11 with Conda on CIs

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
Neither `exec` nor `exec_` is present on the `QTextStreamManipulator` class object in the PyQt5 (5.9.2 to 5.15.8, the latest to date) and PyQt6 (6.4.2, the latest to date).
See https://github.com/spyder-ide/qtpy/issues/402
> Don't make `QTextStreamManipulator.exec_` on PyQt5/6

- qtpy/QtCore.py
The removal looks safe, provided the oldest supported `PySide2` is 5.12.
See https://github.com/spyder-ide/qtpy/issues/405
> PR: Remove patch that may be limited to PySide-5.11a1 only

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/tests/test_qtgui.py
Added
```python
QMouseEvent.pos = lambda self: self.position().toPoint()
QMouseEvent.x = lambda self: self.position().toPoint().x()
QMouseEvent.y = lambda self: self.position().toPoint().y()
QMouseEvent.globalPos = lambda self: self.globalPosition().toPoint()
QMouseEvent.globalX = lambda self: self.globalPosition().toPoint().x()
QMouseEvent.globalY = lambda self: self.globalPosition().toPoint().y()
```
for PyQt6 and PySide6.
And I had to add 
```python
QMouseEvent.position = lambda self: QPointF(float(self.x()), float(self.y()))
QMouseEvent.globalPosition = lambda self: QPointF(float(self.globalX()), float(self.globalY()))
``` 
to PyQt5 and PySide2 to make the event test universal and (consequently, but this was not the required enhancement) bidirectional. This way, I check that the …
> PR: Add mappings for QMouseEvent methods

- qtpy/tests/test_qtpositioning.py
As discovered in PR #413 , as of the release of `qt-main` 6.4.3 on Conda-Forge (conda-forge/qt-main-feedstock#135), the Qt6 Conda jobs are failing because [QtPositioning is no longer included in `qt-main` as of 6.4.3](https://github.com/conda-forge/qt-main-feedstock/pull/135/files#diff-54cf74e113dd3f6d11e092fdb1d888ec82c69bdafbb15cfb6570c83ecad28f33), along with the other QSensors stuff for device sensors.
Therefore, I just went ahead and skipped the test on `QT6` and `conda`. It might be nice to be able to actually check the version, though for that we really should do a proper version comparison on the `QT_VERSION` (for which it would be a good idea to parse it and the other versions in `__init__` to "version_info"-style version tuples, e.g. under `QT_VERSION_INFO` and similar, which …
> PR: Skip QtPositioning tests on Conda Qt >=6.4.3 where its not included

- qtpy/QtGui.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtwidgets.py
Place `QAction`, `QActionGroup`, `QFileSystemModel`, `QShortcut`, and `QUndoCommand` both in `QtGui` and `QtWidgets`.
The rationale. When developing under `PySide6`, one can import `QAction` from `qtpy.QtGui`. When the code moved to `PyQt5`, it fails.
This is a part of the insanely large PR I recently proposed. This way, it would be easier to review the changes.
> PR: Improve compatibility for `QtWidgets` and `QtGui` modules between Qt5 and Qt6 bindings

- qtpy/__init__.py
In addition to `PythonQtError`, `QtBindingsNotFoundError` now also inherits from `ImportError`. This should be easier to catch from outside than a generic `RuntimeError`.
Fixes #412.
> PR: Make `QtBindingsNotFoundError` also inherit from `ImportError`

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
More and more code is initially written for Qt6 and then required to run on Qt5. There are many things introduced or renamed in Qt6. One of them is `QLibraryInfo.location` → `QLibraryInfo.path` and `QLibraryInfo.LibraryLocation` → `QLibraryInfo.LibraryPath`.
Following https://github.com/spyder-ide/qtpy/pull/393, I'd like to port `QLibraryInfo.path` and `QLibraryInfo.LibraryPath` back to Qt5. This way, all the supported flavors have `QLibraryInfo.location`, `QLibraryInfo.path`, `QLibraryInfo.LibraryLocation`, and `QLibraryInfo.LibraryPath` altogether.
> PR: Symmetrize `path` and `location` of `QLibraryInfo`

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
As far as I've noticed, the favorable Qt5 binding was PyQt5, and for Qt6 it's PySide6. They are different in many ways beside the Qt backend. One of the differences is the way to get Python date/time from the Qt one: it's `toPyDateTime`/`toPyDate`/`toPyTime` in PyQt5/6 and one `toPython` to rule them all in PySide2/6.
To ease the transfer from PyQt5 to PySide6, I propose the expansion of https://github.com/spyder-ide/qtpy/pull/169. And some tests for the results, as @CAM-Gerlach has suggested in https://github.com/spyder-ide/qtpy/pull/403#discussion_r1095370537.
> PR: Symmetrize `QDateTime.toPython` and `toPyDateTime`, etc.

- qtpy/QtCore.py
- qtpy/QtGui.py
- qtpy/QtWidgets.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtwidgets.py
- qtpy/utils.py
The help for `QMenu.exec_` reads something like the following (the order might be different, and fully qualified Qt class names might appear):
```plaintext
exec_(...)
exec_(actions: typing.Sequence[QAction], pos: QPoint, at: typing.Optional[QAction] = None, parent: typing.Optional[QWidget] = None) -> QAction
exec_(self) -> QAction
exec_(self, pos: QPoint, at: typing.Optional[QAction] = None) -> QAction
```
The first option here is a static call to `QMenu.exec_`. In the QtPy tests, such a call is never tested. So, here it is. As one might expect, it fails. Use the `_possibly_static_exec` function to fix the errors.
> PR: Use static calls of `exec_` elsewhere where needed, and test them

- .github/workflows/ci.yml
- qtpy/tests/test_compat.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtmultimedia.py
- qtpy/tests/test_qtprintsupport.py
- qtpy/tests/test_qtwidgets.py
- qtpy/tests/test_uic.py
In this PR I have added installation of libs required by qt to setup `QApplication`. For this, I have used [`tlambert03/setup-qt-libs@v1` ](https://github.com/tlambert03/setup-qt-libs). This action is used in few projects testing Qt (like napari) so if new Qt version requires some additional library it will be added without the need to make such a patch in all projects.
> PR: Enable more tests on CI

- .github/workflows/ci.yml
- qtpy/QtWidgets.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtwidgets.py
closes #432
What did you think about this as idea?
> PR: Add wrapers to fix argument name in `QFileDialog` `get*`methods

- qtpy/QtCore.py
- qtpy/_utils.py
- qtpy/tests/test_qtcore.py
To make the new code compatible with `PySide2`, I've made `exec()` for the classes that have `exec_()` functions:
- `QCoreApplication`
- `QEventLoop`
- `QThread`
- `QTextStreamManipulator`
And tests for the calls. Actually, `test_qtextstreammanipulator_exec` and `test_qthread_exec` are far from perfect, but I haven't figured out how to test them.
> Make `exec()` for PySide2

- qtpy/tests/test_uic.py
- qtpy/uic.py
This replaces the custom implementation of qtpy.uic.loadUiType with the one from PySide6. Fixes #439.
> PR: Replace custom implementation with loadUiType from PySide6

- .github/workflows/ci.yml
- .github/workflows/test.sh
* Move macOS CI job with Python 3.7 and pip to use PyQt6 6.5+
* Move CI jobs with Python 3.11 and pip to use PySide6 6.5+
* Ignore `DeprecationWarning` raised inside `pip` vendored `pkg_resources` version (`DeprecationWarning: pkg_resources is deprecated as an API.` message)
Part of #442
> PR: Update bindings upper bound version to 6.5 and ignore `DeprecationWarning` (CI)

- qtpy/QtWidgets.py
- qtpy/_utils.py
- qtpy/tests/test_qtwidgets.py
Surprisingly, I've stumbled upon that in Qt5 and Qt6, `addAction` accepts arguments in different order. So, here's the monkey patch for that.
I've checked other derivatives of `QWidget`, and only `QMenu`, `QToolBar`, and `QLineEdit` have non-trivial `addAction`. I haven't patched the latter, for it hasn't changed between Qt5 and Qt6. So, this is the patch for `QMenu` and `QToolBar`.
I don't actually know how to use the `receiver: QObject` and the `member: bytes` arguments of `addAction`, so I haven't tested them.
> PR: Make `QMenu.addAction` and `QToolBar.addAction` compatible with Qt6 arguments' order

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
> PR: Restore `Qt.ItemFlags` access as `Qt.ItemFlag` alias (PyQt6)

- qtpy/QtGui.py
- qtpy/tests/test_qtgui.py
Mappings for `pos` and `posF` for `QDropEvent` also affect child classes (`QDragMoveEvent`, `QDragEnterEvent`). A mapping to have `position` over Qt5 bindings is done too.
Part of #442
> PR: Add mappings for deprecated `QDropEvent` `pos` and `posF` methods

- qtpy/QtWidgets.py
- qtpy/tests/test_qtwidgets.py
> PR: Restore `QtWidgets.QFileDialog.Options` access as `QtWidgets.QFileDialog.Option` alias (PyQt6)

- qtpy/QtCore.py
- qtpy/QtWidgets.py
- qtpy/_utils.py
- qtpy/tests/test_qtcore.py
- qtpy/tests/test_qtwidgets.py
* Follow-up #448 and #444 
* Fix wrapper functions for `QFileDialog` static methods (used for compatibility with the `dir` vs `directory` kwarg specification)
Need for changes discovered at https://github.com/napari/napari/pull/6164#issuecomment-1688468052 and https://github.com/napari/napari/pull/6164#issuecomment-1689044857
> PR: Improve enum to flags aliasing for PyQt6 and PySide6 > 6.3 and `QFileDialog` static methods kwarg compatibility

- README.md
- qtpy/cli.py
- qtpy/tests/test_cli.py
My proposition of updated README and CLI that explains how to update the pyright configuration to eliminate type checking errors, especially in VSCode.
Solution based on this [comment](https://github.com/spyder-ide/qtpy/issues/352#issuecomment-1170684412) and follows the discussion from my [issue](https://github.com/spyder-ide/qtpy/issues/447).
NOTE:
I couldn't get the pre-commit hooks to run. It seems that some of them are outdated and raise this [error](https://github.com/PyCQA/isort/issues/2077) that has been fixed in newer versions. After updating, however, the yamllint check was throwing errors instead, so I left it as is.
> PR: Update Docs with information on Pyright/Pylance integration and add CLI subcommand to help generate the related config

- .github/workflows/ci.yml
- .github/workflows/test.sh
- README.md
- qtpy/tests/test_qtdatavisualization.py
- qtpy/tests/test_qtnetworkauth.py
* Add CI matrix value to install PyQt extra packages
* Remove setting specific QScintilla version for PyQt6 and instead just install it without version constraint when using the pyqt-extras flag: checking the CI logs the test was being skipped for errors when trying to import `QSci` due to DLL errors or because the specified version was not compatible with the PyQt6 version being installed and then the import failed.
* Add step to review jobs matrix/config values
* Move some jobs to run using latest Qt6 bindings (6.5)
* Update README with testing matrix value section and some improvements to the typing section and the general content
Fixes #383
> PR: Test using `PyQt` extra packages

- qtpy/QtWebEngineWidgets.py
- qtpy/tests/test_qtwebenginewidgets.py
> PR: Fix bug when importing from `PySide6.QtWebEngineCore/QtWebEngineWidgets` (`QWebEngineScrip` vs `QWebEngineScript`) 

- qtpy/QtGui.py
- qtpy/QtWidgets.py
- qtpy/_utils.py
- qtpy/tests/test_qtgui.py
- qtpy/tests/test_qtwidgets.py
Test `QMenu.addAction` with a shortcut of `Qt.Key` type as well. The argument type causes the following error on `PySide2`:
```plaintext
TypeError: 'PySide2.QtWidgets.QAction.setShortcut' called with wrong argument types:
PySide2.QtWidgets.QAction.setShortcut(Key)
Supported signatures:
PySide2.QtWidgets.QAction.setShortcut(PySide2.QtGui.QKeySequence)
```
This is a direct follow-up to #460.
> PR: Make `QAction.setShortcut` and `setShortcuts` accept many types

- qtpy/__init__.py
xref: https://github.com/spyder-ide/qtpy/issues/494
I'm not sure if you like to add things like this, but it is pretty hard to track this bug down.
> PR: Help users understand why PySide 6.8.0 gives a segfault

- README.md
This is because Quansight is no longer one of the main sponsors of this project.
> Replace Quansight logo by CZI one in Readme

- qtpy/QtCore.py
- qtpy/tests/test_qtcore.py
If QtCore.Qt.MidButton works with QtPy and Qt6, then QtCore.Qt.MouseButton.MidButton is expected to work as well.
> PR: Add `QtCore.Qt.MouseButton.MidButton` alias for Qt6

- qtpy/QtGui.py
- qtpy/QtWidgets.py
- qtpy/tests/test_qtwidgets.py
> PR: Ensure `QMenu` and `QToolBar` `isinstance` checks succeed and remove unneeded wrapper classes 

- pytest.ini
When running the package tests with PySide 6, the tests fail because PySide 6 gives a DeprecationWarning, and the pytest.ini settings turn this into an error.  This PR ignores that specific error.
I tried using a `warnings.catch_warnings()` block in `qtpy/QtSql.py` around the deprecated functions, but pytest seems to ignore this.  It might be worth adding such a block anyway.
> PR: Ignore PySide6 `QSqlDatabase.exec` `DeprecationWarning`
