.gitignore, RELEASE.md, qtpy/_version.py, setup.cfg
Similar to those of qtawesome.
This fixes #1.
=> Adding wheel configuration and release instructions

qtpy/QtCore.py, qtpy/QtDesigner.py, qtpy/QtGui.py, qtpy/QtNetwork.py, qtpy/QtPrintSupport.py, qtpy/QtSvg.py, qtpy/QtTest.py, qtpy/QtWebKit.py, qtpy/QtWidgets.py, qtpy/__init__.py, tests/travis.py
Fixes #5
----
Spyder is much more battle tested than qtpy or pyqode, so I prefer to use as much as we can from its shim here.
=> Add improvements and missing imports from Spyder Qt shim

CHANGELOG.md, setup.py
=> Fix links in setup.py and improve changelog

qtpy/QtGui.py, qtpy/QtWidgets.py
=> Import QIntValidator in QtGui and remove it from QtWidgets

qtpy/QtCore.py
This adds compatibility for QItemSelectionModel
=> Add compatibility for QItemSelectionModel

qtpy/__init__.py
@Nodd, I think this is enough, right?
=> Allow QT_API values that are not completely in lower case

qtpy/QtWidgets.py
=> del QtWidgets.QStyleOptionViewItemV4

.ciocheck, circle.yml
I added the full test matrix on linux with circle CI, and it takes about 2 minutes to do everything (plus I added ciocheck).
The next step is to use travis for mac builds only.
@ccordoba12 any comments here?
The failing test is pyside that broke recently... so not related to this.
=> PR: Circle ci expansion

MANIFEST.in
=> PR: Add manifest

.travis.yml, appveyor.yml, circle.yml, qtpy/QtSvg.py
This is done so we can release a new version. Besides, I'm still -1 on issue #46.
=> Use star imports in QtSvg again instead of direct ones (reverts PR #55)

qtpy/_patch/qheaderview.py
=> Add missing copyright header in _patch/qheaderview.py

README.md
=> PR: Update Appveyor badge in Readme because of moving to an org account

qtpy/QtOpenGL.py
Adds a wrapper for the QtOpenGL module for qtpy in reply to issue #101
=> PR: Add a new QtOpenGL module

qtpy/QtCore.py, qtpy/tests/test_qtcore.py
=> PR: Add compatibility for the rename of qInstallMsgHandler to qInstallMessageHandler

README.md
=> PR: Fix typo in Readme.

qtpy/QtSql.py, qtpy/tests/test_qtsql.py
Fixes #135 
----
Fix (my feature request) #135
=> PR: Add QtSql wrapper (incl. test)

qtpy/QtCore.py
=> PR: Add a preventive change for PySide-5.11a2

qtpy/QtMultimediaWidgets.py, qtpy/QtQml.py, qtpy/QtQuick.py, qtpy/QtWebChannel.py, qtpy/QtWebSockets.py, qtpy/QtXmlPatterns.py, qtpy/tests/test_qtmultimediawidgets.py, qtpy/tests/test_qtnetwork.py, qtpy/tests/test_qtqml.py, qtpy/tests/test_qtquick.py, qtpy/tests/test_qtwebchannel.py, qtpy/tests/test_qtwebsockets.py, qtpy/tests/test_qtxmlpatterns.py
Fixes #157.
some qt5 modules (qml, quick, multimediawidgets, webchannel, websockets) + xmlpatterns
=> PR: Add more Qt modules

.circleci/install.sh, appveyor.yml, qtpy/__init__.py, qtpy/tests/test_macos_checks.py
=> PR: Raise error when trying to use the wrong combination of macOS and Qt versions

qtpy/QtCore.py, qtpy/tests/test_qtcore.py
=> PR: Shim PyQt5 QDateTime.toPyDateTime to QDateTime.toPython for compatibility with PySide2

.circleci/config.yml, .circleci/install.sh, .circleci/test-pyqt4.sh, .circleci/test-pyqt5.sh, .circleci/test-pyside.sh, .circleci/test-pyside2.sh, qtpy/__init__.py
=> PR: Make PythonQtError inherit from RuntimeError to be easily catchable

qtpy/QtCore.py, qtpy/tests/test_patch_qcombobox.py, qtpy/tests/test_uic.py
=> PR: Add QtCore.__version__ for PySide2

qtpy/QtWebEngineWidgets.py, qtpy/tests/test_qtwebenginewidgets.py
The latest builds of PySide2 already have it.
=> PR: Restore QWebEngineSettings for PySide2

qtpy/QtGui.py, qtpy/__init__.py
Hello maintainers,
I am using PyQt4-sip==4.19.13 and I find qtpy very useful.
I would like to add support for my version of PyQt without impacting other versions.
Please review PR and let me know if I should change anything. 
I would like to have this PR official in pip ASAP, so let me know if there is anything else I could help with.
Thank you in advance.
Best regards,
Milan
Thank you
=> PR: Add support to PyQt4-sip 4.19.13

qtpy/uic.py
Support python 3.9
Fixes #206 #238
=> PR: Support python 3.9 `custom_widgets` iteration

setup.py
Add `setup.py` classifier info for Python 3.9
=> PR: Update setup.py classifiers

qtpy/QtDatavisualization.py, qtpy/__init__.py, qtpy/tests/test_qtdatavisualization.py
Needed since Windows doesn't do upper/lowercase differentiation for file names
=> PR: `QtDataVisualization` backward compatibility handling on Windows

qtpy/__init__.py, qtpy/tests/test_qtwinextras.py
Fixes https://github.com/spyder-ide/qtpy/issues/248
=> PR: Add handling for QtDataVisualization when missing

qtpy/QtGui.py
=> 'width' need for PyQt6

CHANGELOG.md, qtpy/QtOpenGL.py
- I think this is important so that regular users can know what changed in this major version.
- Also make some lines fit in 79 columns (this is a small nitpick after PR #307).
=> PR: Add "New features" section for version 2.0 to changelog

.github/workflows/ci.yml, .github/workflows/test.sh, qtpy/Qsci.py, qtpy/tests/test_qsci.py
This adds Qsci to the potential imports for qtpy.
Fixes #134
=> PR: Add `Qsci` to the imports

CHANGELOG.md
Follow up for https://github.com/spyder-ide/qtpy/issues/389#issuecomment-1490638629
=> PR: Add missing issue closed for v2.3.1 changelog entry

.github/workflows/ci.yml, pytest.ini
See https://github.com/coverallsapp/github-action/issues/205 and https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
=> PR: Fix coverage errors and macOS jobs

.github/workflows/ci.yml, .github/workflows/test.sh
* Remove Mambaforge usage, update to setup-miniconda v3 and change use of `mamba` for `conda`
* Change apt install command from `libegl1-mesa` to `libegl1-mesa-dev` (following Ubuntu 24.04 package availability)
Fixes #501
=> PR: Remove `Mambaforge` usage and update Linux setup (CI)

SECURITY.md
Update our security policy to reflect the currently supported versions and the modern vulnerability reporting mechanism.
=> Update security policy to modern standards
